version: '3.8'

services:
  lovelace:
    container_name: lovelace
    build:
      context: .
    networks:
      lovelace:
        ipv4_address: 107.50.0.5
    volumes:
      - ./symfony:/app/symfony:cached
      - ./logs/symfony:/app/symfony/var/log:cached
      - ./.:/app
    ports:
      - 8080:80
  mongo:
    image: mongo
    networks:
      lovelace:
        ipv4_address: 107.50.0.6
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=project
    ports:
      - 8881:27017
  mongo-express:
    image: mongo-express
    networks:
      lovelace:
        ipv4_address: 107.50.0.7
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=${MONGO_ROOT_USER}
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=${MONGO_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGOEXPRESS_LOGIN}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGOEXPRESS_PASSWORD}
    depends_on:
      - mongo
    ports:
      - "8888:8081"
networks:
  lovelace:
    driver: bridge
    ipam:
      config:
        - subnet: 107.50.0.0/16
          gateway: 107.50.0.1
